const Constants = {
    "ENDPOINT_UPDATE_PATH" : "http://localhost:5000/api/updateconfig",
    "TOGGLE_RELEASE_TAGGING": "TOGGLE_RELEASE_TAGGING",
    "TOGGLE_FEATURE_TAGGING": "TOGGLE_FEATURE_TAGGING",
    "TOGGLE_CHORE_TAGGING": "TOGGLE_CHORE_TAGGING",
    "TOGGLE_BUGFIX_TAGGING": "TOGGLE_BUGFIX_TAGGING"
}

export default Constants;